version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"

  app-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

