version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    volumes:
      - databaseData:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    networks:
      - defaultNetwork
    
    

  backend:
    container_name: app-backend
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    stdin_open: true
    tty: true
    networks:
      - defaultNetwork
    
volumes:
  databaseData:

networks:
  defaultNetwork:

